# docker compose -f "docker-compose.yml" up -d --build
services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: soil_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '5454:5432'

    soil_fetcher:
        build: ./src
        env_file: ./src/.env
        environment:
            DB_HOST: db
            DB_NAME: soil_db
            DB_USER: user
            DB_PASS: pass
        container_name: soil-moisture-fetcher
        restart: unless-stopped
        depends_on:
            - db

volumes:
    db_data:
