
services:
    # soil-moisture-fetcher:
    #     build: .
    #     container_name: soil-moisture-fetcher
    #     env_file:
    #         - .env
    #     restart: 'no'
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: soil_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '5454:5432'

    soil_fetcher:
        build: ./server
        env_file: ./server/.env
        depends_on:
            - db
        volumes:
            - ./app:/server

volumes:
    db_data:
