# docker compose -f "docker-compose.yml" up -d --build
services:
    db-mosture:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: soil_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '5454:5432'

    soil_fetcher:
        build: ./src
        env_file: ./src/.env
        environment:
            WEBHOOK_URL: https://node-auth-master.youmrabti.com/hooks/webhook
            SMTP_HOST:
            SMTP_PORT: 587
            SMTP_USER:
            SMTP_PASS:
            EMAIL_FROM:
            EMAIL_TO:
            DB_HOST:
            DB_NAME:
            DB_USER:
            DB_PASS:
        container_name: soil-moisture-fetcher
        restart: unless-stopped
        depends_on:
            - db-mosture

volumes:
    db_data:
