# docker compose -f "docker-compose.yml" up -d --build
services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: soil_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '5454:5432'

    soil_fetcher:
        build: ./src
        env_file: ./src/.env
        container_name: soil-moisture-fetcher
        restart: 'no'
        depends_on:
            - db
        volumes:
            - C:/Users/youmt/.config/earthengine:/root/.config/earthengine:ro

volumes:
    db_data:
